1          Starting year
7000           Last year
site.100      Site file name
0             Labeling type
-1            Labeling year
-1.00         Microcosm
-1            CO2 Systems
-1            pH effect
-1            Soil warming
0             N input scalar option (0 or 1)
0             OMAD scalar option (0 or 1)
0             Climate scalar option
1            Initial system
G4            Initial crop
            Initial tree
+150 12/31 ACEQ A





Year Month Option
1            Block #   MLRA 022A 25 yr fire frequency
7000         Last year
25            Repeats # years
1         Output starting year
12           Output month
100.000        Output interval
F            Weather choice
weather.wth
  1  1 GRAZ LRRL,   2 GRAZ LRRL,
  1  3 CROP G4
     3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
  2  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
  3  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
  4  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
  5  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
  6  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
  7  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
  8  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
  9  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 10  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 11  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 12  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 13  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 14  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 15  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 16  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 17  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 18  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 19  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 20  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 21  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 22  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 23  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 24  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
    10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
 25  1 GRAZ LRRL,   2 GRAZ LRRL,   3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRH,
     5 GRAZ LRRH,   6 GRAZ LRRL,   7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRM,
     9 FIRE H, 10 GRAZ LRRH, 10 LAST, 10 SENM,   11 GRAZ LRRH,   12 GRAZ LRRL,
-999 -999 X
