1          Starting year
7000           Last year
site.100      Site file name
0             Labeling type
-1            Labeling year
-1.00         Microcosm
-1            CO2 Systems
-1            pH effect
-1            Soil warming
0             N input scalar option (0 or 1)
0             OMAD scalar option (0 or 1)
0             Climate scalar option
1            Initial system
G1            Initial crop
            Initial tree
+150 12/31 ACEQ A





Year Month Option
1            Block #   MLRA 006 SG 15 yr fire frequency
7000         Last year
15            Repeats # years
1         Output starting year
12           Output month
100.000        Output interval
F            Weather choice
weather.wth
  1  1 GRAZ LRRL,   2 GRAZ LRRM,
  1  3 CROP G1,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  2  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  3  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  4  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  5  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  6  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  7  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  8  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  9  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  10  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  11  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  12  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  13  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  14  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH,   10 GRAZ LRRM, 10 LAST,
    10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
  15  1 GRAZ LRRL,   2 GRAZ LRRM,
     3 FRST, 3 GRAZ LRRH,   4 GRAZ LRRH,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRH, 9 FIRE H,  10 GRAZ LRRM,
     10 LAST, 10 SENM,   11 GRAZ LRRL,   12 GRAZ LRRL,
-999 -999 X
