1          Starting year
7000           Last year
site.100      Site file name
0             Labeling type
-1            Labeling year
-1.00         Microcosm
-1            CO2 Systems
-1            pH effect
-1            Soil warming
0             N input scalar option (0 or 1)
0             OMAD scalar option (0 or 1)
0             Climate scalar option
1            Initial system
G4            Initial crop
              Initial tree
1 1 DRAN 0.3
+150 12/31 ACEQ A





Year Month Option
1            Block #   MLRA 27 SG 15yr fire frequency
7000         Last year
25            Repeats # years
1            Output starting year
12            Output month
100.000        Output interval
F            Weather choice
weather.wth
  1  1 GRAZ LRRX,   2 GRAZ LRRX,
  1  3 CROP G4
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  2  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  3  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  4  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  5  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  6  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  7  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  8  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  9  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  10  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  11  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  12  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  13  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  14  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  15  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  16  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  17  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  18  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  19  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  20  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  21  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  22  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  23  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  24  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL,   10 GRAZ LRRH, 10 LAST,
    10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
  25  1 GRAZ LRRX,   2 GRAZ LRRX,
     3 FRST, 3 GRAZ LRRX,   4 GRAZ LRRM,   5 GRAZ LRRL,   6 GRAZ LRRL,
     7 GRAZ LRRL,   8 GRAZ LRRL,   9 GRAZ LRRL, 9 FIRE H,  10 GRAZ LRRH,
     10 LAST,  10 SENM,   11 GRAZ LRRX,   12 GRAZ LRRX,
-999 -999 X
