1         Starting year
7000           Last year
site.100      Site file name
0             Labeling type
-1            Labeling year
-1.00         Microcosm
-1            CO2 Systems
-1            pH effect
-1            Soil warming
0             N input scalar option (0 or 1)
0             OMAD scalar option (0 or 1)
0             Climate scalar option
1            Initial system
GI4            Initial crop
            Initial tree
+150 12/31 ACEQ A





Year Month Option
1            Block #   mlra 005 25 yr fire frequency
7000         Last year
25            Repeats # years
1         Output starting year
12           Output month
100.000        Output interval
F            Weather choice
weather.wth
  1  3 CROP GI4
     3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  2  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  3  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  4  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  5  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  6  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  7  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  8  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  9  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  10  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  11  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  12  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  13  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  14  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  15  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  16  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  17  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  18  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  19  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  20  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  21  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  22  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  23  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  24  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM,   10 GRAZ LRRL, 10 LAST,
    10 SENM,
  25  3 FRST, 3 GRAZ LRRL,   4 GRAZ LRRM,   5 GRAZ LRRH,   6 GRAZ LRRH,
     7 GRAZ LRRH,   8 GRAZ LRRH,   9 GRAZ LRRM, 9 FIRE H,  10 GRAZ LRRL,
     10 LAST, 10 SENM,
-999 -999 X
